version: '3.4'

services:
  twtnews:
    image: twtnews
    env_file:
      - ./config/.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: